spring:
  datasource:
    url: "jdbc:mysql://49.235.106.220:3306/blogIt?useUnicode=true&characterEncoding=utf-8"
    username: root
    password: Chx123!@#

server:
  servlet:
    context-path: /blog
